### ISSUE TITLE
Drag in drop in row

### ISSUE THREAD

**Issue by dgastudio** [ANovokmet/svelte-gantt#102]
Hi,

Is it possible to allow dragging only within one row?

i mean allow only horizontal drag, not vertical

Thanks

**Comment by V-Py** [comment]
Hello, yes it is possible manually using the tasks event api : 

```
gantt.api.tasks.on.changed(function([data]){
           if(data.targetRow.model.id != data.sourceRow.model.id){
              handle your exception here
           }
        })
```
If you want a parameter in the gantt options to never allow dragNdrop in other row, it doesn't exist for now.

**Comment by V-Py** [comment]
Hello, did I answer your interrogation ? If so or no answer in the next week I'll close this issue

**Comment by dgastudio** [comment]
yes, thank you!
