### ISSUE TITLE
Is timeranger show different day?

### ISSUE THREAD

**Issue by kesyous** [ANovokmet/svelte-gantt#103]
I want to set timeranger on another days on gantt. Only time can be entered in the options. How can I set it?

**Comment by V-Py** [comment]
You are not able to set timeranger dates to other days except the current one ? 
Timeranger `from `and to `properties ` accept any number as parameter so you should be able to pass any timestamp.
Can you show me the way you define your timerangers please ?

**Comment by kesyous** [comment]
![A1](https://user-images.githubusercontent.com/57670197/193508525-accb1b58-883e-4db4-a292-35e7a7384700.PNG)
![A2](https://user-images.githubusercontent.com/57670197/193508541-3866d988-7b77-492c-80c7-8108041b60ef.PNG)

**Comment by V-Py** [comment]
If you are using momentjs, replace time by moment and specifiy the format of your string to avoid errors.
Something like moment('2022-10-03 12:00', 'YYYY-MM-DD hh:mm', true)

**Comment by kesyous** [comment]
![A5](https://user-images.githubusercontent.com/57670197/193510251-d71b4bc3-f710-4656-bd5b-740c812d1ac7.PNG)
![A6](https://user-images.githubusercontent.com/57670197/193510261-cf2cd4fc-8f6b-4c6f-a849-c517949420af.PNG)

Gantt is currently work when i set time before 12:00 but isn't currently work when i set time after 12:00

![A3](https://user-images.githubusercontent.com/57670197/193510341-104fc34a-c2d3-4afb-a118-0bc24fafb64c.PNG)
![A4](https://user-images.githubusercontent.com/57670197/193510348-74674d06-fcea-4385-aad0-37b5a08358e8.PNG)

**Comment by V-Py** [comment]
Yes, in the moment documentation it is specified you should use `H HH` or `k kk` instead of `h hh` if you want to use 24 hours time. https://momentjscom.readthedocs.io/en/latest/moment/01-parsing/03-string-format/
I'm closing this issue!
