### ISSUE TITLE
4.0.8-beta looks invalid in NPM

### ISSUE THREAD

**Issue by Azbesciak** [ANovokmet/svelte-gantt#104]
It is not runnable, imports do not work (there is no `index.js` in the node package, and importing from `src` also fails the build.

**Comment by V-Py** [comment]
Yes I'm on it currently, use the 4.0.7 until further notice

**Comment by Azbesciak** [comment]
Yeah, I wanted to but I still had issues after installing any version, like 
```
Error: node_modules/svelte-gantt/types/core/drag/dragDropManager.d.ts:2:26 - error TS2307: Cannot find module 'svelte/store' or its corresponding type declarations.

2 import { Writable } from 'svelte/store';
                           ~~~~~~~~~~~~~~


Error: node_modules/svelte-gantt/types/core/drag/dragDropManager.d.ts:9:48 - error TS2344: Type 'SvelteRow' does not satisfy the constraint 'EntityType'.

9     constructor(rowStore: Writable<EntityStore<SvelteRow>>);
                                                 ~~~~~~~~~


Error: node_modules/svelte-gantt/types/core/store.d.ts:1:26 - error TS2307: Cannot find module 'svelte/store' or its corresponding type declarations.

1 import { Readable } from 'svelte/store';
                           ~~~~~~~~~~~~~~


Error: node_modules/svelte-gantt/types/core/store.d.ts:29:44 - error TS2344: Type 'SvelteRow' does not satisfy the constraint 'EntityType'.
  The types of 'model.id' are incompatible between these types.
    Type 'string | number' is not assignable to type 'number'.

                                              ~~~~~~~~~

```
Typescript 4.8.4, npm 8.5.0, node 16.14.2

**Comment by V-Py** [comment]
Right, this problem is related to #101. 
My understanding of the problem seems to be that the library is compiled as commonJS, which seems to be an issue since Node version > 16 and so with the last SvelteKit versions.
I'm currently on both these problems, but my skills in Node.js and in build configuration aren't that strong, and since this isn't my library originally I'm having a bit of trouble resolving it.

Trying to solve it asap, wouldn't mind some help if somebody got a better understanding of this problem 😁

**Comment by Gismo150** [comment]
It looks like the 4.0.8-beta was built using the "build" command from the package.json which runs "rollup -c" but previous packages were build with the "node tools/build" command as mentioned in the readme at the very bottom.

The following image compares the npm package contents of 4.0.8-beta with 4.0.7-beta. 4.0.7-beta was built using the latter command.
![grafik](https://user-images.githubusercontent.com/22026608/196435023-3b4892f5-19cf-42e3-8018-9d50ac172891.png)

Probably you can publish another package using the latter command?

**Comment by V-Py** [comment]
Fixed, thanks 😄
