### ISSUE TITLE
Fix date after gantt update

### ISSUE THREAD

**Issue by kesyous** [ANovokmet/svelte-gantt#105]
Hi,
In gant, I write the changes to the database, but when the page is refreshed, I want the date and view to remain. Can I keep this data in browser memory with local storage?

**Comment by V-Py** [comment]
Well, you can surely do this manually ? I don't understand your question, you want the Gantt to handle your data for you ?
After saving in your database, you have to retrieve your data on page load, and init the gantt with it ? 
If you want to use local storage to store/retrieve your data, you also can but it's kinda up to you,. The Gantt is just here to render your data, not handle them for you !
