### ISSUE TITLE
hide dependency

### ISSUE THREAD

**Issue by TrungLeThanh** [ANovokmet/svelte-gantt#106]
Hi,
Can I hide the dependencies between tasks when I uncollapse the parent task?
![image](https://user-images.githubusercontent.com/78038680/195755533-ee2c6b3a-d703-4d36-bd53-53025771836e.png)

Thanks

**Comment by V-Py** [comment]
Hello, I might not have understand your question, the dependencies are shown only if you describe them in the dependencies array in the options of the Gantt ?
If you don't want to see these dependencies, remove them ?

Or your question is more about a specific action to perform on "uncollapse" of a parent row ?

**Comment by TrungLeThanh** [comment]
Sorry, I mean when I close a parent row, its dependencies persist like the image below
don't close:
![image](https://user-images.githubusercontent.com/78038680/195780317-d915c2c5-f435-426a-b5ee-299a9c6fef0a.png)

closed: 
![image](https://user-images.githubusercontent.com/78038680/195780715-80fab94a-dad2-4cab-a4ff-f78f978e4a16.png)

**Comment by V-Py** [comment]
Sorry I didn't answer before, this looks like a good improvement to me ! adding the correct tag, don't hesitate trying a PR on this subject won't have time to treat it soon

**Comment by BlueFoxPrime** [comment]
Seems easy to change. I will take a look at it.

**Comment by ahmadshiddiqn** [comment]
so, has this been fixed yet? seems the PR was already 5 months ago and this bug still occurs on my SvelteKit project (I downloaded the package at the end of last month)

**Comment by V-Py** [comment]
I merged the PR this morning, sorry for the delay, try it out that should be fixed by now
