### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by fabiiomiiguel** [ANovokmet/svelte-gantt#11]
Hello, first of all thank you for your amazing gantt.

I have found some bugs related with your tools/build.js, but I can't create a pull request..

Greetings, Fábio

**Comment by fabiiomiiguel** [comment]
I have a local branch with the minor bugs fixed :)

**Comment by ANovokmet** [comment]
Hello, thanks for taking interest in this library and fixing the issue. What seems to be the problem with creating the pull request?

**Comment by fabiiomiiguel** [comment]
I don't know why, in that day, I was unable to create, sorry for disturbing

**Comment by ANovokmet** [comment]
Closing this issue as the PR was created and merged.
