### ISSUE TITLE
Typos might be the reason of some issues

### ISSUE THREAD

**Issue by Masatoshi** [ANovokmet/svelte-gantt#110]
I am testing @4.0.8 and found many typos.
And there are also import failures.

on src/core/store.ts
```
import { writable, Readable, derived } from 'svelte/store';
import { SvelteTask } from './task';
import { SvelteRow } from './row';
import { SvelteTimeRange } from './timeRange';
```

should be 
```
import { writable, readable, derived } from 'svelte/store';
import type { SvelteTask } from './task';
import type { SvelteRow } from './row';
import type { SvelteTimeRange } from './timeRange';

```

many writable, readable are written 1st capital large.
importing interfaces should be as type import.

**Comment by V-Py** [comment]
Hi, thank you very much but don't bother testing 4.0.8 it was building error using the wrong command. I published the 4.0.9 two days ago which should be ok now
