### ISSUE TITLE
Example referred to in the readme has already been removed

### ISSUE THREAD

**Issue by swssl** [ANovokmet/svelte-gantt#122]
The readme refers to ./public/index.html as an example. The readme's history shows, that the file was removed in 74e9ade3b398aaaf4fc5b1bb136e8e4bb8334ca6  and possibly replaced in the ./docs/public folder which in turn was again removed in 17051376479bf77c51a6e81ae3b71f9796237568

**Comment by BlueFoxPrime** [comment]
Hi, the html using the latest compiled js lives in /docs/index.html
It is served as a static file with the following command "demo:start": "sirv docs --dev -s"

**Comment by V-Py** [comment]
I'm closing this
