### ISSUE TITLE
Javascript files...?

### ISSUE THREAD

**Issue by ChR-iSz** [ANovokmet/svelte-gantt#127]
Hi, Where i can find the javascript files which you note in your readme ?

**Comment by V-Py** [comment]
Hi, which files are you talking about ?

**Comment by ChR-iSz** [comment]
Hi,

for systems without npm: 
index.iife.js

**Comment by V-Py** [comment]
Sorry for the late answer, to generate this file, run node tools/build in svelte-gantt, it will generate a dist folder locally in which you will find the index.iife.js file!
