### ISSUE TITLE
zoomLevels examples or more details on how to implement?

### ISSUE THREAD

**Issue by labs20** [ANovokmet/svelte-gantt#128]
Hi.

I couldnt find any examples or detailed documentation about zoomLevels.

Can you please point me to some more content about it?

Thanks

**Comment by BlueFoxPrime** [comment]
Hey, there is a discribtion of accepted arguments in the docs.

Defaults from Gantt.svelte:
`    export let zoomLevels = [
		{
			headers: [
				{ unit: 'day', format: 'DD.MM.YYYY' },
				{ unit: 'hour', format: 'HH' }
			],
			minWidth: 800,
			fitWidth: true
		},
		{
			headers: [
				{ unit: 'hour', format: 'ddd D/M, H A' },
				{ unit: 'minute', format: 'mm', offset: 15 }
			],
			minWidth: 5000,
			fitWidth: false
		}
	];`

**Comment by V-Py** [comment]
I'm closing this

**Comment by labs20** [comment]
Ok. 

I'd suggest to pick this code from that file and add it to the documentation section, as its hard to find it where it is now.

Thanks
