### ISSUE TITLE
[New Feature] Resize and move multiple items at the same time

### ISSUE THREAD

**Issue by BlueFoxPrime** [ANovokmet/svelte-gantt#129]
I changed the selection manager and draggable class to allow resizing and draggin of multiple items.
Items can be selected with ctrl + left click and will be unselected with a click on an empty space. If a single item is clicked (without crtl), items will be unselected and that item will be the new selection.

![Animation_](https://user-images.githubusercontent.com/112826784/206273087-1efa9aa2-e16d-4ade-b67b-f93cd10a743d.gif)

**Comment by V-Py** [comment]
Awesome man 🤩, thanks a lot, I'll review it and merge it asap (probably tomorrow, I'm looking at the issues right now)
I wasn't finding time to work on the repo recently, but your PR is giving me new motivation 🔥

**Comment by BlueFoxPrime** [comment]
I will do my best to continue but I am still learning. Feel free to make suggestions to my code :-)

I think dependencys need to be updated and the whole thing should be converted to sveltekit.
Are you working on any of this?

**Comment by BlueFoxPrime** [comment]
I will do my best to contribute but I am still learning. Feel free to make suggestions to my code :-)

I think dependencys need to be updated and the whole thing should be converted to sveltekit.
Are you working on any of this?

// closed this on accident :D

**Comment by BlueFoxPrime** [comment]
There is two bugs that I noticed:
1. Its possible to dragg items to "the other side" and then all items resize incorrectly --> possibility to do that should be removed
2. The "not clicked items" are not resized exactly as the clicked one, they are lagging slightly behind. Problem becomes visible when removing magnetOffset.

@V-Py please reopen

**Comment by V-Py** [comment]
Yeah, I'm currently finishing to work on the sveltekit demo version, and noticed some of these while testing!

**Comment by V-Py** [comment]
Hey @BlueFoxPrime, do you have any update on the correction of these bugs ? 😃

**Comment by BlueFoxPrime** [comment]
Hey, for 1. Mostly fixed, I also intend to preserve the possibility of 'overrezising. There is a bug still when reverting back from 'overrezising' on offset tasks. For 2. I think it might just be a few pixels off. I haven't looked into it in depth. I wanted this to be finished before the holidays but didn't manage. Will do so from 27.12. as I get back home.
