### ISSUE TITLE
Be able to set task area column width

### ISSUE THREAD

**Issue by labs20** [ANovokmet/svelte-gantt#133]
Must needed. Like `columnWidth: 40px`

Thanks

**Comment by BlueFoxPrime** [comment]
I dont understand what you are talking about. Please be more specific and include an example.

**Comment by V-Py** [comment]
To be fair I don't understand it either, clarify this ASAP @labs20 please or I'll close it

**Comment by labs20** [comment]
Hi. Sorry for the delay, I was away for the hollydays.

I mean that would be great if I could set a predefined width for columns in the task area, instead of having it calculated by the comp. This could bring more control of the look of the gantt.

Thanks.

**Comment by ANovokmet** [comment]
You could use the from, to, and width properties to fine-tune the timeline width for columns to have your desired width. For example, if you had columns every 15 minutes, and if you displayed 24 hours, that would display 96 columns. If you wanted the column to be 20px wide, the timeline width should be `96 x 20 = 1920`. If there is a more compelling argument to do it another way we'll look into it.
