### ISSUE TITLE
Vertical scroll on table area in sync with task area 

### ISSUE THREAD

**Issue by labs20** [ANovokmet/svelte-gantt#134]
As of now, you can only scroll at the task side of the gantt. It is very important that the user could use the mouse wheel at the table side as well, while keeping both vertical scroll areas in sync.

Thanks!

**Comment by V-Py** [comment]
I'm not 100% sold on this demand, and certainly not an important problem at the moment.

**Comment by labs20** [comment]
Hi, my test users are complaining ( as users as they are =] ) that they can't scroll the gantt, but this is just because they are rolling the mouse wheel over the rows tree area.

Users = clients, and clients are always... sad, but you know. =]

Thanks!

**Comment by ANovokmet** [comment]
This could be done by binding the `mousewheel` event to the table (because `scroll` does not trigger when an element has `overflow: hidden`). If it is crucial we can look again into implementing it.
