### ISSUE TITLE
[Bug] 'move' and 'moveEnd' tasks not fired when task is being moved over the chart

### ISSUE THREAD

**Issue by Vitalik549** [ANovokmet/svelte-gantt#140]
Tested on svelte example page: https://anovokmet.github.io/svelte-gantt/events , Events tab
Move task from the source code is never triggered when user is dragging (drag and drop) task within the chart.
`gantt.api.tasks.on.move((task) => console.log('Listener: task move', task));`

I would expect it to get triggered similar to 'mousemove' event. 

My use case: I tried to disable vertical task dragging (between rows), so the idea was to keep same style.translate Ypx of the node, but unfortunately move event is not fired, same as `node.addEventListener('drag', onDrag);` event.  

Triggered events when moving a task: 
```
[task] hover {id: 4, resourceId: 4, label: 'Auditing', from: 1672290900000, to: 1672299000000, …}
Events.svelte:143 Listener: task change {task: {…}, sourceRow: {…}, targetRow: {…}}
Events.svelte:144 Listener: task changed [{…}]
```

**Comment by Vitalik549** [comment]
P.S. I have no idea why `node.addEventListener('drag', onDrag);` (and other drag events, like `dragstart`, etc) is not fired upon drag and drop in `taskElementHook`, though `mouseenter`, `click` and other events works just fine. Would appreciate any comments on that)

**Comment by labs20** [comment]
This is live already?

**Comment by V-Py** [comment]
@labs20 , nop still waiting for #129 to be fixed to publish the new version on npm
The changes are available on the repo here though.

**Comment by labs20** [comment]
ok. 
this is the only way to know were the user is draging or streching a task right? 

Because my code at `changed` can't tell the difference between the two operations and I'm having the task duration altered by my code when I got the `ev.task.model.to` date.

Any ETA on that?

Thanks

**Comment by V-Py** [comment]
Well I did manage to do it via storing the infos on `change` and comparing with the infos on `changed` : 

```
gantt.api.tasks.on.change(function([data]){
            slot_selected.set(data.task);
        });

gantt.api.tasks.on.changed(function([data]){
            let task_moved = data.task.model;

   const start_days_difference_temp = task_moved.from.diff($slot_selected.from, 'days');
    const end_days_difference_temp = task_moved.to.diff($slot_selected.to, 'days');
    let start_days_difference   = 0;
    let end_days_difference     = 0;
    let etirement = 'none';

    if(start_days_difference_temp != end_days_difference_temp){
        if(start_days_difference_temp < 0 && end_days_difference_temp < 0){
            etirement = 'cancel';
        // }else if(start_days_difference_temp > 0){
        }else if(start_days_difference_temp > 0 || start_days_difference_temp < 0){
            etirement = 'start';
        }else if(start_days_difference_temp == 0){
            etirement = 'end';
        }
    }
})

```

**Comment by V-Py** [comment]
But not a clean way to do it, I have to admit

**Comment by labs20** [comment]
Thanks for the effort!

We are not in production yet, mostly internal tests, so we can wait a week or two for the fix in the new release.

Thanks for your attention.
