### ISSUE TITLE
Cannot read properties of undefined (reading 'MomentSvelteGanttDateAdapter')

### ISSUE THREAD

**Issue by kevinismus** [ANovokmet/svelte-gantt#151]
Hi, I am trying to follow the SvelteKit example but kept getting the error:

**Cannot read properties of undefined (reading 'MomentSvelteGanttDateAdapter')**

Can anyone help me with this? Thank you!

**Comment by PabloRuizCuevas** [comment]
@kevinismus could you share the solution? I'm having the same problem
