### ISSUE TITLE
vertical thick line

### ISSUE THREAD

**Issue by kesyous** [ANovokmet/svelte-gantt#153]
I want to show vertical thick line on some clocks. As seen in the picture. How can i do it?

![gantt_alinti](https://user-images.githubusercontent.com/57670197/212905514-0414dc93-18a0-4231-ae38-dd96a8b2ff15.PNG)

**Comment by BlueFoxPrime** [comment]
Hey! It would be easiest to use Timeranges and modify the css in TimeRange.svelte according to your needs.
I don't see much use to generally impelement such a feature.

**Comment by kesyous** [comment]
![alinti2](https://user-images.githubusercontent.com/57670197/213359566-fef884f4-2088-4109-b05b-c787cf7ffa96.PNG)

which class can I add to show it?

**Comment by BlueFoxPrime** [comment]
Hey, if you havent found out by now... I meant the "timeranges" module. You can define timeranges objects and assign them to svelte gantt (see the docs).

**Comment by kesyous** [comment]
![gantt_timerange](https://user-images.githubusercontent.com/57670197/216911941-eae82e49-a3e6-4134-a922-9b863469f837.PNG)

Style tag in TimeRange.svelte file. Which attribute can I set to get the vertical thick line?

**Comment by ANovokmet** [comment]
We've improved this in v4.1:

1. Add a timerange with `from==to`, `resizable: false` and some class eg. `time-range-lunch`:

```js
gantt.$set({
  timeRanges: [
        {
            id: 0,
            from: time('10:00'),
            to: time('10:00'),
            classes: 'time-range-lunch',
            label: 'Lunch',
            resizable: false,
        }
  ]
});
```

2. In your CSS file add a style for this class:

```css
.time-range-lunch {
    border-left: 1px solid black;
}
```

This will render just a straight black line in the timeline.
