### ISSUE TITLE
React / Vanilla JS question

### ISSUE THREAD

**Issue by AlexBHarley** [ANovokmet/svelte-gantt#16]
Love this gantt chart, it's awesome, thanks for all your work _and_ under the MIT license. 

My issue is I need it in React. I see a few options:

- fork it, rip out svelte stuff and replace with JSX
- collaborate with you making it React compatible
- collaborate with you making it vanilla JS, that way anyone (React / Vue / Svelte) can import it.

Curious to hear your thoughts on this.

**Comment by ANovokmet** [comment]
The built module is already library agnostic - It's made with Svelte but the dist files have no other dependencies except moment.js (and I hope that will change too, see https://github.com/ANovokmet/svelte-gantt/blob/gh-pages/dist/lib.js), and that is one of the reasons why I decided to use Svelte.

I could however help you import it in a React project, and fix any issues preventing it from being used with React. Another good option is writing a wrapper library for React.

**Comment by AlexBHarley** [comment]
Gotcha, thanks for getting back to me. Makes sense that the bundle is agnostic actually. I'll take some time to see how it plays with React and let you know!

**Comment by fabiiomiiguel** [comment]
The package works great with Vue.js

**Comment by ANovokmet** [comment]
And it works well with Angular, too :)

**Comment by AlexBHarley** [comment]
Slowly starting to get the React adapter together, would you want it part of this repository or my own?

**Comment by ANovokmet** [comment]
> Slowly starting to get the React adapter together, would you want it part of this repository or my own?

I think it's better for that to be another repository.

**Comment by darekeapp** [comment]
@ANovokmet I have tried the code you had provided me in React and it does not seem to work. Code:

App.js
```
import React from 'react';
import SvelteGanttReact from './SvelteGanttReact';

const App = props => {
  return (
    <div>
      <h1>Testing Gantt</h1>
      <SvelteGanttReact></SvelteGanttReact>
    </div>
  );
};
export default App;
```

SvelteGanttReact.js
```
import React, { Component } from 'react';
import { SvelteGantt } from 'svelte-gantt';

class SvelteGanttReact extends Component {
  constructor(props) {
    super(props);
    this.myRef = React.createRef();
  }

  componentDidMount() {
    const node = this.myRef.current;
    const gantt = new SvelteGantt({
      // target a DOM element
      target: node,
      // svelte-gantt options
      props: {
        tasks: [],
        rows: [],
        from: moment(),
        to: moment().add(1, 'day')
      }
    });
  }

  render() {
    return <div ref={this.myRef} />;
  }
}

export default SvelteGanttReact;
```

I get the following output:

![image](https://user-images.githubusercontent.com/78209159/106269878-07da6f80-6225-11eb-9f71-242f780a386e.png)

The think the problem is the `const gantt` is not being used anywhere...`'gantt' is assigned a value but never used`. But not sure how to solve it. Any advice?

**Comment by ANovokmet** [comment]
@darekeapp I've sent you an example piece of code on how to load `svelte-gantt` in a react component I've made in codesandbox.io. The missing thing is `svelte-gantt.css` which is obviously missing from the snippet. Please refer to the `svelte-gantt` installation instructions. I am not a react developer and I'm not aware of the best practices on loading CSS into react apps, but usually you use a `<link>` tag in the `<head>` element.

**Comment by ngohoang1254** [comment]
Can you send me that codesandbox.io. I need build this chart in react js.

**Comment by ngohoang1254** [comment]
> @darekeapp I've sent you an example piece of code on how to load `svelte-gantt` in a react component I've made in codesandbox.io. The missing thing is `svelte-gantt.css` which is obviously missing from the snippet. Please refer to the `svelte-gantt` installation instructions. I am not a react developer and I'm not aware of the best practices on loading CSS into react apps, but usually you use a `<link>` tag in the `<head>` element.

Can you send me that codesanbox.io. I have problem build this chart in React.

**Comment by willnaoosmith** [comment]
Tried using it on ReactJS, kept getting `Module not found: Error: Can't resolve 'svelte-gantt'` even after installing it and importing as said on README.md
