### ISSUE TITLE
how to make the label visible in viewport even if the start date is off screen?

### ISSUE THREAD

**Issue by JasnaTodorovic** [ANovokmet/svelte-gantt#164]
I have a use case where it's common to have long-running tasks and i want to be able to see all the ones that are currently in progress. I can see the task element on the chart, but its label is way off the chart (at the start point of the task) and I have to change the visible date range in order to see what the task actually is. Is there a way to have the label be displayed within the viewport even if its start date is off screen?

See screenshot for example (the bottom 3 tasks)
<img width="803" alt="Screen Shot 2023-03-24 at 6 13 34 PM" src="https://user-images.githubusercontent.com/5452904/227653332-a16a2531-fd20-4c69-97a5-00867b88108e.png">

**Comment by V-Py** [comment]
Hey, sorry for the late response, would be a nice enhancement for sure! 
Will take a look at this asap but feel free to do a PR on this if you wish
