### ISSUE TITLE
How Can I Auto scroll during drag

### ISSUE THREAD

**Issue by cryingnavi** [ANovokmet/svelte-gantt#165]
How Can I Auto scroll during drag?

Is it not possible to move the scroll automatically when dragging to the end of the screen?

<img width="1405" alt="스크린샷 2023-03-25 오후 4 09 08" src="https://user-images.githubusercontent.com/1834819/227702681-9e254b4a-260d-4e46-87d5-8d54522c027e.png">

**Comment by V-Py** [comment]
Hi, sorry for the late response, this would be indeed a nice feature to add!
Did add the enhancement tag since it is not available at the time, but the feature shouldn't be that hard to implement

**Comment by ANovokmet** [comment]
Implemented in v4.1
