### ISSUE TITLE
local dev demo

### ISSUE THREAD

**Issue by dimasbk** [ANovokmet/svelte-gantt#166]
firstly, im a total beginner on svelte. I tried cloning this repo into my local machine and tried running the demo with `npm run demo:dev` like on the readme but it doesnt show anything (blank) the i tried cloning one more time but this time i used steps from https://github.com/ANovokmet/svelte-gantt/issues/49. Now when i ran  `npm run demo:dev`  it showed the chart twice as the picture below

![image](https://user-images.githubusercontent.com/83223898/228099253-4bbbe44e-3ceb-4406-9bdf-b3506276c379.png)

when i close the project and reopen it it showed blank as shown below

![image](https://user-images.githubusercontent.com/83223898/228100949-34ec36bd-551e-4d02-8fe4-f56fc9f86030.png)

how do i fix this? or maybe the proper way to setup the demo on local?

**Comment by V-Py** [comment]
Hi and sorry for the late response, I'll review the local dev/build process as soon as I can

**Comment by ANovokmet** [comment]
In v4.1 running `npm run autobuild` in the root folder and `npm run dev` in the demo folder will be enough. #175
