### ISSUE TITLE
How to clear or reset the gantt??

### ISSUE THREAD

**Issue by labs20** [ANovokmet/svelte-gantt#167]
I have a gantt that has its rows and tasks filtered on a client interface, that goes to the server, compute the filters and bring back to the client the filtered rows and tasks, for example, "show me only tasks of type B and C".

I'm using vue, by the way.

When I came back from server, on a watch I build the data for the gantt in one function and then set it to it, like this:
```
let [headers, rows, tasks, dependences, ranges] = this.processValue(new_val);
this.gantt.$set({
    from: this.inicio,
    to: this.final,
    tableHeaders: headers,
    rows: rows,
    tasks: tasks,
    dependences: dependences,
    timeRanges: ranges,
});
```
But the gantt wont refresh right. And if I hit F5 just after I try to do this update, the gantt renders perfectly with the same data that I tryied to apply via $set.

How to refresh the gantt? How to remove rows and tasks?

**Comment by V-Py** [comment]
I'm going to look into this bug more next week, as I have some time to work on the Gantt, and I also need to address this problem for personal projects

**Comment by labs20** [comment]
Hello, my friend. I'v got the chance to play with this? Any good news? =]

Thanks!

**Comment by labs20** [comment]
Hi. Sorry to ask again, but I'm running close to a dead line here, so I need to get this working ASAP. I've been looking at the source code and it seems that there is no kind of "reset" function or behaviour. I could figure out that if I update from a payload with fewer tasks and rows to one with more tasks it will crash at:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'model')
    at get_key_3 (index.js:3929:1)
    at update_keyed_each (index.js:411:1)
    at Object.p (index.js:4173:1)
    at update (index.js:352:1)
    at flush (index.js:321:1)
```

Looks to me that some index confusion may be the cause of the problem. I would expect that `gantt.$set` should replace any given property and setting new rows and tasks should redraw it to reflect the new payload.

Please, can you tell me if there are planings to fix this, or if this will not be adressed for now, so I can make a decision on what turn to make?

Thank you!

**Comment by V-Py** [comment]
Hi, I'm sorry but my professional schedule didn't allow me to take any time for this project. I'm still quite busy right now but can just try to help you on this. 
Your bug doesn't seem to be related to any index confusion, you seems to use either task.model or row.model in a each loop on an empty task/row object somewhere after refreshing your data. 

Where are you using the gantt.$set method ?  Because right now I'm using svelte-gantt on multiple projet and didn't encounter your bug.

Don't know if you can provide any more code so I can try to debug it on my side ?

**Comment by ANovokmet** [comment]
Sorry for the late reply. 
Your approach is good and the gantt should work like that, but I could not reproduce the issue.
To clear the gantt using `gantt.$set({ tasks: [], rows: [] })` works. If tasks display weird, try to use `gantt.refreshTasks()`.

We can debug it further if you send the example of the data that the gantt is being refreshed with. I am using a version of svelte-gantt in an application and it displays data that is constantly being changed and filtered by the back-end with no issues.
