### ISSUE TITLE
This project still active?

### ISSUE THREAD

**Issue by labs20** [ANovokmet/svelte-gantt#168]
Hi, with all due respect for the time of everyone involved in produce such a nice component, and above all, distribute it for free so the whole comunity could enjoy its efforts, but, as for the time the not answered questions have, since january, I'd like to kown if this is still an ongoing project or if it is in pause right now.

Asking because some of the issues I'm facing are show stoppers and I must take the decision to continue or to move along to find another vue gantt.

Really appreciate your efforts until here and this is a great comp. Hope its not over.

Thanks.

**Comment by V-Py** [comment]
Problem is we lack contributors on this project. @ANovokmet is basically inactive, and I tried my best maintaining it during almost a year. But these past months I didn't have as much time as before for this project, and the lack of contributors/help is also a bit discouraging. 
So I won't say the project is inactive per say, but it could benefit having more contributors to not rely on my availability, that's for sure

**Comment by labs20** [comment]
Thanks for your answer. I'm not a svelt guy, so contribute in code is kinda difficult to me, but I do understand you point.

My biggest issue is the lack of a "reset" function, looks like the gantt was build for a single shot of data, and I'm using it on a high traffic situation, where users are filtering, adding, removing and editing tasks that are persisted on a database all the time.

I cant do a reliable refresh with new packs of data incoming from server, it seems like the internal indexing of the tasks and/or rows gets confused and breaks. I was (am) really hopping for some mistake on my side, but the minute I hit F5 and the page refreshs with the same data, the gantt renders without any problems. Im kinda lost and in a hurry, for the deadline aproachs.

Any help or direction, if you could spare some, will be much appreciated.

Thanks!
