### ISSUE TITLE
how to apply latest fix

### ISSUE THREAD

**Issue by dyuhob** [ANovokmet/svelte-gantt#174]
Hi. 
after installing and importing svelte-gannt by npm
i am using your gantt-chart in my vue2 project 

but i have problem displaying only 30 days in one month.
i have seen you fixed that issue.

i copied files in src folder of latest github version and overwited files in types folder of svelte-gantt in node_module. 
but nothing changed.

is there other way to apply latest fix to my local file?

thanks

**Comment by V-Py** [comment]
Hey, can you give me a bit more details: which version have you installed, and which fix is it?

**Comment by dyuhob** [comment]
I have installed 4.0.9-beta version which is uploaded on https://www.npmjs.com/package/svelte-gantt. 
and i need fix #136.

i guessed that fix does not applied to 4.0.9. 
so i copied files in src on github main and overwrited files on node_module folder.
but it doesn't work.

**Comment by dyuhob** [comment]
i think fix #136 is applied on  https://www.npmjs.com/package/svelte-gantt.
is there any plan to publish latest version to npm? or 
can you let me know how to modify index.js file on node_module?

**Comment by ANovokmet** [comment]
> i think fix #136 is applied on https://www.npmjs.com/package/svelte-gantt. is there any plan to publish latest version to npm? or can you let me know how to modify index.js file on node_module?

Yes, sorry. Published the latest version to npm right now.

**Comment by dyuhob** [comment]
Error : module parse failed occurred.  is there any other loader to be installed?

**Comment by ANovokmet** [comment]
> Error : module parse failed occurred. is there any other loader to be installed?

Could you post the whole error message and where it occurs?

**Comment by dyuhob** [comment]
Module parse failed: Unexpected token (419:8)
You may need an appropriate loader to handle this file type.
|        * @default false
|        */
|       is_svg = false;
|       /** parent for creating node */
|       e = undefined;

each time i run into error, i deleted parts which error occurred. but there are too many;
should i edit webpack.config.js file?

**Comment by ANovokmet** [comment]
> Module parse failed: Unexpected token (419:8) You may need an appropriate loader to handle this file type. | * @default false | _/ | is_svg = false; | /_* parent for creating node */ | e = undefined;
> 
> each time i run into error, i deleted parts which error occurred. but there are too many; should i edit webpack.config.js file?

If you push the whole setup to a repo somewhere I'll be able to take a look. Otherwise I can't tell what is wrong since the error message does not tell me much

**Comment by dyuhob** [comment]
I pushed the whole setup to my github repo ('gantt' project). thanks

**Comment by ANovokmet** [comment]
This is what I found in your project:

```vue
<template>
  <div></div>
</template>
<script>
 import {
    MomentSvelteGanttDateAdapter,
    SvelteGantt,
    SvelteGanttDependencies,
    SvelteGanttTable,
    SvelteGanttExternal
  } from 'svelte-gantt'

    export default {
        name: 'Home',
        components: {
            MomentSvelteGanttDateAdapter,
      SvelteGanttExternal,
      SvelteGantt,
      SvelteGanttDependencies,
      SvelteGanttTable,
        },
        data() {
            return {
                
            };
        },
    };
</script>
<style>
</style>
```

Component included in svelte-gantt is not a vue component so they should can't be used in this way. You should obtain a reference to a DOM node and then initialize the gantt. In vue it would look something like this:

```vue
<template>
  <div ref="yourElementRef"></div>
</template>

...
onMounted() {
    this.gantt = new SvelteGantt(this.$refs.yourElementRef, props);
}
```

For more information see https://vuejs.org/guide/essentials/template-refs.html and look up "how to use 3rd party library on an element in vue". This repo has examples of other frontend libraries using svelte-gantt.

**Comment by dyuhob** [comment]
thank you!
the way you told me, gantt works.

**Comment by dyuhob** [comment]
sorry for reopening.
I have registerd svelte-gantt for component. but i didn't use it as components.
I used 'document.querySelector' instead of refs like this.

function (){
      new SvelteGantt({
          // target a DOM element
          target: document.querySelector('.GanttPlace'),
          // svelte-gantt options
          props: options,
        });
}

I'm not used to composition API. so I updated my repo as option API.
can you taking a look at my repo again?
thanks

**Comment by ANovokmet** [comment]
Ok, I took a look. When using vue-loader (webpack) you need to set `babel-loader` to run for the .js files, otherwise some javascript features do not work, in this case those are class properties. In your project it is:

```js
// webpack.dev.conf.js
const devWebpackConfig = merge(baseWebpackConfig, {
  module: {
    rules: [
      ...utils.styleLoaders({ sourceMap: config.dev.cssSourceMap, usePostCSS: true }),
      // I added the following
      { 
        test: /\.js$/,
        loader: 'babel-loader'
      },
    ]
  },
```

After that there are other issues (optional chaining is not supported). Supposedly upgrading webpack resolves this issue. Another thing you can try is using the `@babel/plugin-proposal-optional-chaining` plugin, I tried that but it resulted with:

```

 ERROR  Failed to compile with 4 errors                               8:45:07 AM

Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/home/ante/Desktop/gantt/node_modules/@babel/helper-plugin-utils/lib/index.js:69:11)

```

All in all this is not an issue related directly to `svelte-gantt`, but with how webpack loads files. Maybe try upgrading it to v5, I would do it but the last time I did it it was no trivial task, as a lot of other dependencies had to be updated.

**Comment by dyuhob** [comment]
thanks! eventually it's webpack problem... 
I think it's risky to update webpack in project cause it has a lots of other libraries with it.
rather than that I will use new version of svelte-gantt when I need gantt-chart in other project.
