### ISSUE TITLE
v4.2 - Columns wrong alignment at right end scrollbar

### ISSUE THREAD

**Issue by martinfruehmorgen** [ANovokmet/svelte-gantt#187]
Hello,

First of all thanks for all the recent updates!

When using a higher minWidth (f.e. 5000), the columns at the right end of the gantt are misaligned.
See the attached screenshot. It is based on the large dataset demo (https://anovokmet.github.io/svelte-gantt/large-dataset) with 5000 minWidth.
![Screenshot 2023-10-17 122144m](https://github.com/ANovokmet/svelte-gantt/assets/14124317/a70cf149-a675-4603-8191-09d6417bd6a6)

Any chance to adjust this?

Thanks!
Martin

**Comment by ANovokmet** [comment]
Hey, thanks for reporting the bug. I'll look into it soon. Which browser are you using?

**Comment by martinfruehmorgen** [comment]
Edge Version 118.0.2088.46

**Comment by ANovokmet** [comment]
Fixed in v4.2.1, thanks again 😃
