### ISSUE TITLE
Feature Request - Create task by drag in the timeline

### ISSUE THREAD

**Issue by martinfruehmorgen** [ANovokmet/svelte-gantt#190]
Hello,

Is there a chance to implement creating a new task by dragging in the timeline (in a row)?

Thanks again!
Martin

**Comment by ANovokmet** [comment]
Yes, this makes sense. It's also a feature available on some other Gantt chart components.

**Comment by ANovokmet** [comment]
This is going to be a feature in v4.3.0. See README and the example: https://anovokmet.github.io/svelte-gantt/create-tasks
