### ISSUE TITLE
Remove task(s)

### ISSUE THREAD

**Issue by minmur** [ANovokmet/svelte-gantt#191]
I can't find a way to remove the task. There is `updateTask` and `updateTasks`, but no `removeTask` or similar. Reloading entire page seems overkill.

**Comment by ANovokmet** [comment]
Makes sense, will add it to the next release. Thanks!

**Comment by jonashan** [comment]
And the ability to remove column aswell :)

**Comment by ANovokmet** [comment]
> And the ability to remove column aswell :)

Do you mean removing a specific date from the timeline?

**Comment by ANovokmet** [comment]
Now you can use `gantt.removeTask(123)` or `gantt.removeTasks([123, 124, 125])` to remove tasks by ID.
