### ISSUE TITLE
Reset or Clear GanttChart

### ISSUE THREAD

**Issue by dyuhob** [ANovokmet/svelte-gantt#195]
if chart get wrong timeformat in from, to , tasks, chart explode.
after that,
even though I have pushed correct data into options and executed chart.  it didn't work properly.

reloading page is only way to reset chart.

I'm using vue. so I want to reset chart when components were destroyed.
Is there any way to reset or clear chart without reloading or closing page?

**Comment by ANovokmet** [comment]
Well in vue you can force a rerender of a component like this 
```
<template>
  <MyComponent :key="componentKey" />
</template>
<script>
...
    data() {
        return {
            componentKey: 0,
        }
    },
    methods: {
        rerender() {
            this.componentKey++;
        },
    }
...
</script>
```

**Comment by dyuhob** [comment]
but ganttChart does not used as components in vue.
although I did re-render wrapper div, chart was not fixed.
i hope there are methods to reset chart or ways to re-import index.js

**Comment by dyuhob** [comment]
I have solved this problem through method to destory instance
let ganttInstance = new SvelteGantt({
 target: ~
 option: ~
})
ganttInstance.$destroy()
