### ISSUE TITLE
The header is divided at the desired time with a scroll to the right.

### ISSUE THREAD

**Issue by mohamadjomah** [ANovokmet/svelte-gantt#196]
I am trying to divide the header so that it is every 20 minutes, but I am facing a problem that the columns are compressed side by side. I want the table to expand to the right with the ability to drag or scrolling.

see the following picture:

![Screenshot 2023-12-13 134005](https://github.com/ANovokmet/svelte-gantt/assets/83618430/f013b59b-a2a5-4f68-b926-8c7107910e90)

**Comment by leCheveuCodeur** [comment]
Hi, that sounds like my maximum duration problem managed by Gantt 👉  https://github.com/ANovokmet/svelte-gantt/issues/192
It's probably the minWidth that must be beyond its maximum...

**Comment by ANovokmet** [comment]
Does not look like a bug to me, when fitWidth is true columns are resized to fit on the screen. Try setting `fitWidth: false`, and `minWidth` to some big number, eg. `minWidth: 10000`.
