### ISSUE TITLE
Draw the strokes like the column-header-cell instead of using background-image

### ISSUE THREAD

**Issue by fabiiomiiguel** [ANovokmet/svelte-gantt#20]
Hello :) 

Maybe it will be nice, if instead of using sg-columns svelte-1clwlpk with background-image, you draw one row with something like column-header-cell with height 100%. That will allow to style the strokes with css. 

What you think?

![image](https://user-images.githubusercontent.com/27894544/104854001-77369200-58fc-11eb-99a5-d96fe51277eb.png)

**Comment by ANovokmet** [comment]
This is actually how it used to be, but since the main goal for `svelte-gantt` I had, was for it to be as performant as possible, and these lines can be the cause of way too many divs in the DOM being created. What I should do is to provide more options for styling these columns.
