### ISSUE TITLE
Expanded only work correctly for the first row

### ISSUE THREAD

**Issue by Ben-Ford-z** [ANovokmet/svelte-gantt#205]
Hi,

Thank you for generating such a nice gant, I want to report that when rows are created with expanded:false, the 2nd row doesn't show any tasks. I added a few screenshots.

Ben 

when started:
![image](https://github.com/ANovokmet/svelte-gantt/assets/158278959/253d4e09-650b-4101-93b2-e75c6134f402)
when opened:
![image](https://github.com/ANovokmet/svelte-gantt/assets/158278959/4c6b8d3e-88a4-46f6-9e5f-3e61300dff1a)

**Comment by ANovokmet** [comment]
Fixed in v4.3.0
