### ISSUE TITLE
Custom styling for the whole gantt chart in svelte with tailwind or custom css?

### ISSUE THREAD

**Issue by tanasievlad246** [ANovokmet/svelte-gantt#208]
Is there a way to style the gantt chart with tailwind or custom css? whatever I try it does not work, I am trying to set the horizontal row header styles to style the backgrounds and text color for my darkmode and light mode with tailwind. I have also tried using regular css with the `:global` handles but nothing works. the header of the labels column does not change background via css or tailwind, neither the rows labels.

**Comment by ANovokmet** [comment]
Hmm, it should work, it can be done with normal CSS, although you might `!important` some styles. For tailwind, I suppose it depends on its unused CSS removal feature.
This is an example that works https://github.com/ANovokmet/svelte-gantt/blob/main/demo/src/routes/events/%2Bpage.svelte#L236 - there is a style applied to the row header when the row is hovered over.

If you keep having the issue please post an example repo with the issue.
