### ISSUE TITLE
Height auto

### ISSUE THREAD

**Issue by fabiiomiiguel** [ANovokmet/svelte-gantt#21]
This is how gantt stays if we don't set the height.

![image](https://user-images.githubusercontent.com/27894544/104854335-f7112c00-58fd-11eb-8a24-c08dc638206c.png)

I could put height auto, simply using:

`
.sg-timeline-body {
    flex: 0 1 auto !important;
 }
`

![image](https://user-images.githubusercontent.com/27894544/104854322-e660b600-58fd-11eb-8e74-b54becdaa5d8.png)

Maybe should be something to include by default, or maybe using an optional prop.

**Comment by ANovokmet** [comment]
Does your container element have a defined height?

**Comment by fabiiomiiguel** [comment]
Nop the container is only display: flex; flex-direction: horizontal, and with that css on sg-timeline-body we don't need to set any height, I think that could be nice feature

**Comment by ANovokmet** [comment]
I've tested this in a new project. Changed sg-timeline-body `flex: 1 1 0` to `flex: 1 1 auto`, which will prevent it from having a 0 height.

Thank you @fabiiomiiguel for finding and reporting this issue!
