### ISSUE TITLE
Custom task component

### ISSUE THREAD

**Issue by khang3052002** [ANovokmet/svelte-gantt#210]
Hi everyone, I want to custom task component. I work with React, how to do it? Thanks for support

**Comment by ANovokmet** [comment]
You can use `taskElementHook` to access the element belonging to a task, and bootstrap a react component. Not sure about react but I've done it with angular.

Similar example is here https://github.com/ANovokmet/svelte-gantt/blob/main/demo/src/routes/events/%2Bpage.svelte#L150

Another thing you should add is the `update` method, that triggers when task data updates (but the element is reused):

```js
        taskElementHook: (node, task) => {
            const component = bootstrapReactComponent(MyReactComponent, node); // I don't know
            component.props.task = task;

            return {
                update(data) {
                    console.log('[task] update');
                    component.props.task = task;
                },                
                destroy() {
                    console.log('[task] destroy');
                    component.destroy();
                }
            }
```
