### ISSUE TITLE
scaling manually

### ISSUE THREAD

**Issue by leducminhthe** [ANovokmet/svelte-gantt#215]
Can I block task scaling manually?

**Comment by ANovokmet** [comment]
No. I believe there has been a regression. The relevant code is here https://github.com/ANovokmet/svelte-gantt/blob/main/src/entities/Task.svelte#L236, a new property to allow it is needed, which I'll add as soon as possible.

**Comment by leducminhthe** [comment]
thank you very much

**Comment by ANovokmet** [comment]
Fixed in v4.3.0
