### ISSUE TITLE
Fix: querySelector usage in selectTask() throws Uncaught DOMException

### ISSUE THREAD

**Issue by gubeils** [ANovokmet/svelte-gantt#216]
### Issue Description

While invoking `selectTask()` in `src/Gantt.svelte`, the method throws an `Uncaught DOMException`. The issue is due to an invalid selector string being passed to `querySelector`.

#### Error Message:
Uncaught DOMException: Failed to execute 'querySelector' on 'Element': 'data-task-id='50'' is not a valid selector.

#### Location
The issue occurs at line 567 of `src/Gantt.svelte`.

### Proposed Solution
The current selector:
```javascript
`data-task-id='${id}'`
Should be updated to use a proper [attribute selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) syntax:
`[data-task-id='${id}']`
```
Enclosing the attribute selector in square brackets should resolve the Uncaught DOMException error, allowing querySelector to match elements as expected.

**Comment by ANovokmet** [comment]
Thank you! You are right.

Related, I don't like the relevant code that queries the DOM to select a task...

I'll get to fixing it as soon as possible.
