### ISSUE TITLE
Dragging of tasks does not deselect previous selected task

### ISSUE THREAD

**Issue by t0ms3n** [ANovokmet/svelte-gantt#226]
When dragging is enabled, the previously selected task is dragged as well. This even works for tasks which do not have dragging enabled.

**Steps to reproduce:**
  - Select (click) any task
  - Start dragging of another task
  - => Both tasks are moved together

**It is reproducible in the demo:**
![image](https://github.com/ANovokmet/svelte-gantt/assets/14198376/6c7ed690-e722-4a08-a7f8-ac3fa3d9eb2d)

**Expected behaviour:**
Only the task on which the drag is started is dragged.

_Optional:_
Maybe we can select multiple tasks by any way and then we can drag them togehter.

**Comment by gubeils** [comment]
I also met the same issue

**Comment by ANovokmet** [comment]
It is going to be fixed in v4.4.0, to move (and select) multiple tasks you will need to hold ctrl.

**Comment by gubeils** [comment]
@ANovokmet 
Hello, I have currently selected the three tasks in the image below. Could you please advise on how to retrieve the list of selected tasks via an API?

"svelte-gantt": "^4.4.0",


![Image](https://github.com/user-attachments/assets/0a4b262a-8d75-4458-8940-dee6495b1abb)
