### ISSUE TITLE
Task selected class

### ISSUE THREAD

**Issue by ghost** [ANovokmet/svelte-gantt#24]
Whenever a task is clicked on or dragged/moved, the following CSS class always stays: `.sg-task.selected.svelte-19txnoa`. It would be good if and when the user clicks out somewhere else on the page (not necessarily on another task - anywhere on the page really), for the selected class to be removed from the task. I think this may require some event listener (but not exactly sure).

**Comment by ANovokmet** [comment]
Thanks for reporting this issue. You're right. There's an exposed method `selectTask(id)` but there is no method that allows you to unselect a task. For outside click, we need to add an event listener to `document.body` and check if the click falls inside a task.

**Comment by ghost** [comment]
Can you show an example please where clicking out of the task unselects it please?

**Comment by ANovokmet** [comment]
I've decided to hold on to that feature because it's more complex to do effectively. For now, you can make the handler yourself and use `gantt.unselectTasks()` to deselect them.

**Comment by ghost** [comment]
@ANovokmet Okay, thanks. For all these issues you are fixing, how do I get these updates like for the `sticky` option? Do you need to publish them to npm and bump the version number?

**Comment by ANovokmet** [comment]
@darekeapp Yeah, pretty much. Going to do it tommorrow. You can always pull the repo and build it yourself, or download https://github.com/ANovokmet/svelte-gantt/tree/master/docs/dist.
