### ISSUE TITLE
strange behavior with timeRanges

### ISSUE THREAD

**Issue by mschrembs** [ANovokmet/svelte-gantt#29]
Hi,
I pass several timeRanges to the gantt:
![image](https://user-images.githubusercontent.com/2779041/116044113-cf560080-a670-11eb-82bd-0c2b8b5a3ebf.png)

The gantt first loads the timeRanges:
![image](https://user-images.githubusercontent.com/2779041/116044517-4ee3cf80-a671-11eb-8417-6a7ee6898397.png)

When I change the day, a timeRange is still there, even if it was the day before:
![image](https://user-images.githubusercontent.com/2779041/116044587-628f3600-a671-11eb-952f-c363771ef93e.png)

I would have expected the timeRanges to only be there on the defined days.

Thank you.

**Comment by nitish-darji** [comment]
Hello, 

I'm facing same issue when change view and have more than one timeRanges then only first timeRange object updated.

Also I've try gantt.refreshTimeRanges(); but not success.

Just reference below function call internal from lib

         function refreshTimeRanges() {
		timeRangeStore._update(({ ids, entities }) => {
			ids.forEach(id => {
				const timeRange = entities[id];
				const newLeft = columnService.getPositionByDate(timeRange.model.from) | 0;
				const newRight = columnService.getPositionByDate(timeRange.model.to) | 0;
				timeRange.left = newLeft;
				timeRange.width = newRight - newLeft;
			});
			return { ids, entities };
		});
	}

Please help me out any workaround.

Thanks in advance.

**Comment by ANovokmet** [comment]
Interesting, I've just tried the demo with multiple time ranges and I did not experience any issues. Any chance you share the rest of your gantt configuration?

**Comment by ANovokmet** [comment]
Were there any errors in the console? I've fixed an error when time ranges get destroyed which could result in a stuck view.

**Comment by nitish-darji** [comment]
thanks @ANovokmet for quick reply

I'm working on angular and svelte-gantt@3.0.4-beta version 

please check below attached demo link
[https://stackblitz.com/edit/angular-fj36mp](url)

after upgrade latest version now it's working as expected (except one issue when build project then one error occur as below)
node_modules/svelte-gantt/types/modules/table/tableHeader.d.ts:1:27

investigate error then found node_modules/svelte-gantt/types/modules/table/tableHeader.d.ts file import { SvelteRow } from "src/core/row"; when I replace with import { SvelteRow } from "../../core/row"; then it's working fine

Again thanks @ANovokmet

**Comment by ANovokmet** [comment]
@nitish-darji thanks for the heads up on this error, I'll be investigating it.

**Comment by V-Py** [comment]
Hello @nitish-darji, do you still experience this issue cause after some tests I can't reproduce it either with the current version ? 
Thanks in advance :)

**Comment by V-Py** [comment]
No answer and not able to reproduce the bug described
