### ISSUE TITLE
API won't return tasks that use a string as an id

### ISSUE THREAD

**Issue by yannikstauffer** [ANovokmet/svelte-gantt#36]
I've been trying to use a `string` (uuid) instead of a `number` to identify my tasks and rows. This somehow seems to be broken though:
When using my test data as shown below then the component will load and display everything as expected.
As soon as I try to access a task event via API (i.e. `gantt.api.tasks.on.select`) though, the callback is run but only receives an empty object instead of the task. When changing the ids to some numbers then everything works properly again.

I tried to look into your code but I am not familiar enough with javascript to figure out what the issue might be.

```javascript
import { time } from '../utils';

export const data = {
    rows: [{
        id: "bda66280-7a1b-4c63-baaa-fcd59fda7628",
        label: "Petunia Mulliner"
    }],
    tasks: [{
        id: "d4a5e677-ac25-4266-879d-2694e861df07",
        resourceId: "bda66280-7a1b-4c63-baaa-fcd59fda7628",
        label: "LPCVD",
        "from": time("9:00"),
        "to": time("11:00"),
        classes: "orange"
    }],
    dependencies: []
}
```

**Comment by labs20** [comment]
This fix may work for rows, but its not working for tasks. And if I give numeric ids for my tasks, the gantt wont refresh when I get a new payload from the server.

**Comment by leCheveuCodeur** [comment]
Yes, it is currently not possible to update a task using the updateTask method.
If you use this method, the task is hidden. The only solution is to reset the entire gantt.

**Comment by labs20** [comment]
@leCheveuCodeur  What's your strategy to reset the gantt?

**Comment by leCheveuCodeur** [comment]
You need to re-set gantt using the set method, passing all rows and tasks back to it.
To save on queries, you can strocker an array and just update the task concerned, then set gantt again.

**Comment by labs20** [comment]
Yeah, its what I'm tryingo to do, but when I reset from a scenario with fewer tasks to one witch many more tasks, the gantt wont refresh right, sometimes it keeps the old tasks, and when I do vice versa, from a tree with many tasks to a smaller task tree, it keeps the older tasks too. 

The funny funny thing is that if I hit F5, it refreshs and renders itself correctly, with the same payload that it has previously failed.

**Comment by leCheveuCodeur** [comment]
`// Fix for FireFox
setTimeout(function(){ 
    $('.sg-table ').css('width',301)
  }, 2);`
  IF you're on Firefox we had this refresh problem that we had to fix by simulating a change in row size, see if that helps...

**Comment by labs20** [comment]
I'm on chrome, but will test it anyway, thanks!

**Comment by labs20** [comment]
No joy. When I update the gantt from many tasks to fewer, it leaves the last old ones. Looks like no cleaning is in place when you use "set" again.

And those wont do what you'd expect:
```
                       this.gantt.$set({
                            rows: [],
                            tasks: [],
                            dependencies: [],
                        });
                        this.gantt.$set({
                            rows: false,
                            tasks: false,
                            dependencies: false,
                        });
                        this.gantt.$set({
                            rows: null,
                            tasks: null,
                            dependencies: null,
                        });
```
