### ISSUE TITLE
Source code for the demo project

### ISSUE THREAD

**Issue by dondre** [ANovokmet/svelte-gantt#37]
Maybe I'm not able to find it, but can someone give me the source code for this.'

https://anovokmet.github.io/svelte-gantt/#/tree

Trying to get this to run in SvelteKit hasn't been fun -_-

**Comment by ANovokmet** [comment]
It is here: https://github.com/ANovokmet/svelte-gantt/tree/master/docs/src

**Comment by slokhorst** [comment]
Moved to [demo/src](https://github.com/ANovokmet/svelte-gantt/tree/master/demo/src) I think?
