### ISSUE TITLE
Styles are missing when using in ES6 import

### ISSUE THREAD

**Issue by MrTango** [ANovokmet/svelte-gantt#39]
Whenn i follow the way to import ES6 style in my App.svelte file:

import { SvelteGantt, SvelteGanttTable } from 'svelte-gantt';

It works, but most of the styles for the tasks are missing.
Shouldn't they be also included when I'm having tasks in the Gannt or do I really have to include them directly from node_modules my self?

**Comment by ANovokmet** [comment]
Currently, you need to include the styles yourself. From `node_modules/svelte-gantt/css/svelteGantt.css`.

Some styles for tasks really are missing, examples use https://github.com/ANovokmet/svelte-gantt/blob/master/docs/gantt-default.css, I'll make it so tasks are blue by default.

**Comment by ANovokmet** [comment]
As of version `4.0.0` styles get injected and do not need to be included.
