### ISSUE TITLE
Dependencies module

### ISSUE THREAD

**Issue by mindok** [ANovokmet/svelte-gantt#4]
Cool library thanks!
Is the dependencies module currently wired up? I followed the code as best I could but couldn't see how to get it going.

**Comment by ANovokmet** [comment]
It worked in the first versions but I decided to remove it as I didn't find it as a feature I would want to focus on.

Is this something that keeps you from using this component? If yes I will for sure wire it up again promptly.
![image](https://user-images.githubusercontent.com/9156853/80116851-bfe83700-8586-11ea-990f-13986605852c.png)

**Comment by mindok** [comment]
Hi Ante,
I will need something like this in a few weeks. I am linking the project / tasks to a map view and want to represent the dependencies in the project with lines on a map as well as on the gantt chart:
![image](https://user-images.githubusercontent.com/8754819/80177806-507a5200-862f-11ea-8a7b-b01a34fa7b97.png)

If there's anything I can do to help let me know. I will need a bit of guidance though - I'm new to Svelte.

**Comment by ANovokmet** [comment]
Will close this issue, as basic dependencies will be implemented.
