### ISSUE TITLE
Show modal form when mouse hover on gantt

### ISSUE THREAD

**Issue by kesyous** [ANovokmet/svelte-gantt#40]
I want to show when mouse hover a information modal form on a gantt chart item. How i can do it?

**Comment by ANovokmet** [comment]
I'm soon adding a new option to gantt, it is going to let you apply events to the DOM node of each task:
```js
const options = {
    ...
    taskElementHook: (node, task) => {
        
        function onHover() {
            console.log('hover', task);
        }

        node.addEventListener('mouseenter', onHover);

        return {
            destroy() {
                console.log('destroy');
                node.removeEventListener('mouseenter', onHover);
            }
        }
    }
    ...
}
```

It is basically a [svelte action](https://svelte.dev/docs#use_action).

**Comment by nettenm** [comment]
Hi,
when we can expect to get that feature? It would be nice, if we could give some kind of HTML-Template with URLs, Buttons, Functions etc. which renders onClick.

Thanks for the awesome work :)

**Comment by ANovokmet** [comment]
> Hi, when we can expect to get that feature? It would be nice, if we could give some kind of HTML-Template with URLs, Buttons, Functions etc. which renders onClick.
> 
> Thanks for the awesome work :)

The `taskElementHook` feature is up. You could use it to add any event to tasks and append any other element (perhaps a modal) to `document.body`.

You could also do whatever you want on task select, see https://anovokmet.github.io/svelte-gantt/events

**Comment by kesyous** [comment]
> > Hi, when we can expect to get that feature? It would be nice, if we could give some kind of HTML-Template with URLs, Buttons, Functions etc. which renders onClick.
> > Thanks for the awesome work :)
> 
> The `taskElementHook` feature is up. You could use it to add any event to tasks and append any other element (perhaps a modal) to `document.body`.
> 
> You could also do whatever you want on task select, see https://anovokmet.github.io/svelte-gantt/events

Thanks :)
