### ISSUE TITLE
Time Ranges Resize and Time Range Lable box Click event

### ISSUE THREAD

**Issue by nitish-darji** [ANovokmet/svelte-gantt#46]
Hello,

is there any way I can generate time ranges resize event and get time range object with resize time, also time range label box click event and get time range object

I've try but no success

Please help me out

Thanks in advance

**Comment by V-Py** [comment]
Hello, so to understand your needs correctly, you asked for :
- accessible timeRange resize event which pass the timeRange object
- accessible timeRange label click event which pass the timeRange object

Is that right ?
What do you mean by "resize time" ?

**Comment by V-Py** [comment]
Since you didn't reply in the last 14 days, I'll add the above functionalities  (resize event, label click event) and consider the issue fixed after that
