### ISSUE TITLE
version 4.0.3-beta generate two October

### ISSUE THREAD

**Issue by zhaofang** [ANovokmet/svelte-gantt#48]
![image](https://user-images.githubusercontent.com/6812077/144005941-0a85cbf5-b60c-42ea-ad0e-3cf45764d495.png)
Why the header was rendered for two october?

**Comment by ANovokmet** [comment]
When I removed moment from the lib, there were some issues left with timezones and headers. I'm working on it. Can you please tell me your timezone and header configuration?

**Comment by zhaofang** [comment]
timezone is UTF+8;

![image](https://user-images.githubusercontent.com/6812077/144818100-fa54dfcd-133f-4482-a5b3-c578dab85ae0.png)


some configuration:
rows: [],
tasks: [],
headers: [
  {unit: "month", format: 'YYYY年MM月'},
],
fitWidth: true,
columnUnit: "day",
columnOffset: 1,
from: moment('2021-09-01'),
to: moment('2022-02-28'),
minWidth: 2000,
rowHeight: 30,
rowPadding,

**Comment by ANovokmet** [comment]
Thanks for reporting this bug, `svelte-gantt` currently has an issue with months because it takes a month as a 30 day duration, when it actually varies from 28 to 31, not going to be an easy fix for me, but I'll do my best

**Comment by Primenotes** [comment]
@ANovokmet Hey, I am thinking about using svelte-gantt for my project.
The correct display of month is crucial, any idea when you plan to address this issue?
I think that I could manage to implement calender weeks myself.

**Comment by V-Py** [comment]
The display of months should be good with the last update (4.0.6 beta), let me know if it's not the case 😄

**Comment by glutamate** [comment]
@V-Py the problem is gone for months but persists for quarters

![Screenshot 2022-06-20 at 21 28 07](https://user-images.githubusercontent.com/43804/174673656-7a54421b-0178-452c-91bb-a6215f82b732.png)

```
          columnOffset: 14,
          columnUnit: "day",
          magnetUnit: "day",
          magnetOffset: 1,
          headers: [
            {
              unit: "month",
              format: "YYYY[Q]Q",
              offset: 3,
            },
            { unit: "month", format: "MM", offset: 1 },
          ],
```

 and years

![Screenshot 2022-06-20 at 21 29 45](https://user-images.githubusercontent.com/43804/174673881-6c12cbfc-3f0c-4020-b365-2397220b84d5.png)

```
          columnOffset: 14,
          columnUnit: "day",
          magnetUnit: "day",
          magnetOffset: 1,
          headers: [
            {
              unit: "year",
              format: "YYYY",
              offset: 1,
            },
            { unit: "month", format: "[Q]Q", offset: 3 },
          ],
```

in the second screenshot, the two events are actually in 2022, but displayed in 2021.

Maybe reintroducing moment or something equivalent as a dependency could facilitate a lot of these calculations.
