### ISSUE TITLE
Local dev environment

### ISSUE THREAD

**Issue by ManadayM** [ANovokmet/svelte-gantt#49]
Hey,

Let me begin with a big thank you for generously open-sourcing your hard work around Gantt charts. There are few free options available out there so really appreciate the efforts and the intention.

I tried running the demo/docs project but found the following console errors. There seems to be an issue around Svelte Routing.

![Screenshot 2021-12-06 at 5 48 34 PM](https://user-images.githubusercontent.com/521134/144844818-7a0b3b42-f40c-4d79-8a1a-6185ad72cdc1.png)

I'm planning to consume, enhance, and contribute back to this project. Could you please let me know the steps / provide me with a document to set up the project for local development? I followed this but it seems it is not up to date https://github.com/ANovokmet/svelte-gantt#development-build.

Thanks in advance.

Manaday

**Comment by ANovokmet** [comment]
Sorry for the outdated docs. For development using the demo it is best to run two scripts: `npm run autobuild` to build svelte-gantt and `npm run demo:dev` to build and serve the demo at localhost:5000

**Comment by ManadayM** [comment]
Thank you for your reply @ANovokmet. I'm still unable to make it run due to the `missing global variable names` warning/error. In the browser console, it throws `svelteRouting is not defined` error. Am I missing something?

I also noticed that if I remove `demo:autobuild` from this script `"demo:dev": "run-p demo:start demo:autobuild"` then I can run the demo project at localhost:5000 but I'm sure that is an outdated build as `index.js` there doesn't have `svelteRouting` and `svelteGantt` IIFE args.

**Comment by ANovokmet** [comment]
Did you try running `npm install` in `demo/` directory?

**Comment by ManadayM** [comment]
Yes, I did that. I received a `compiler.js` related error after that and to fix that I found I should `rollup-plugin-svelte` to at least version `6.1.1`. I did that as well. Now, I see further warnings and errors in the terminal but am also able to run the demo project locally.

This is how my terminal output looks like.

![Screenshot 2021-12-07 at 3 07 32 PM](https://user-images.githubusercontent.com/521134/145004498-1575f572-4a48-42eb-9886-b1787d0090a7.png)

Below are the setup steps I have performed to run this project locally (with some warnings).

1. `npm install` in the root directory.
2. `npm run build` in the root directory. This will generate the build artifacts in the `dist` directory.
3. `npm install` inside `demo` directory.
4. `npm i rollup-plugin-svelte@6.1.1` inside `demo` directory to upgrade the plugin version to fix the `compiler.js` related error.
5. `npm run autobuild` from the root.
6. `npm run demo:dev` from the root.

Please let me know if these steps are correct or not. I've fairly limited experience with both Svelte and Rollup as of now. I hope to improve at both of them and contribute back.

Once again thank you for your help @ANovokmet.

**Comment by ANovokmet** [comment]
Cloned into a new folder to test.
I did everything the same as you but except 2. which I didn't do, and as 4. I used `npm i -D rollup-plugin-svelte@latest` which fixed the error. And I'm getting no errors there. And then the demo is served at `http://localhost:5000/svelte-gantt/`. With no Reference errors in the console.

**Comment by ManadayM** [comment]
Installing the latest rollup plugin for Svelte fixed the remaining issues. Now, I am able to run the demo project. Thank you for your great help. 🙏🏼
