### ISSUE TITLE
Cannot read properties of undefined (reading 'height') 

### ISSUE THREAD

**Issue by varadharajanviji** [ANovokmet/svelte-gantt#50]
Hey
     Thank you for the generous open-source, i am getting the following error while i try to add task from API using updateTasks method.
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'height') which leads to `getHeight(model) {
            return this.row(model.resourceId).height - 2 * this.rowPadding;
        }` yes i have mapped children array id to resourceId, thank you

**Comment by ANovokmet** [comment]
Sounds like there is a task with unknown resourceId

**Comment by kesyous** [comment]
> Sounds like there is a task with unknown resourceId

I also have the same problem. It gives this error when the resource id is bigger than 10 records in the incoming data.

**Comment by kesyous** [comment]
> > Sounds like there is a task with unknown resourceId
> 
> I also have the same problem. It gives this error when the resource id is bigger than 10 records in the incoming data.

The reason for the problem I had was that the machine table number in the database and the number in the tasks list did not match. I solve this problem.

**Comment by varadharajanviji** [comment]
I got this error when my row and task id was in random integer, i had to work around row and task ids to sequential order(1,2,3.... so on), strange. probably it has something to do with this error #36

**Comment by V-Py** [comment]
If related to the problem with string id #36 might be fixed now with db6eda850acca522e2a2e0671230d64dac070044
