### ISSUE TITLE
Week view is not display fitWidth

### ISSUE THREAD

**Issue by kesyous** [ANovokmet/svelte-gantt#52]
Hello,
I can't show the weekly view in a compressed form, but the gantt looked like that in old versions. In the new version, when I click on the bar above the dates, it switches to that view. How can I get that fixed view to come?

**Comment by ANovokmet** [comment]
You need to set both `fitWidth: true` and `minWidth` to something small like `minWidth: 400`

**Comment by kesyous** [comment]
> You need to set both `fitWidth: true` and `minWidth` to something small like `minWidth: 400`

Thanks
