### ISSUE TITLE
DependencyModel - stroke and strokeWidth property is not working as mentioned in document

### ISSUE THREAD

**Issue by urvesh86** [ANovokmet/svelte-gantt#54]
In my project I have integrated the dependency module of gantt chart. But what I observe `stroke` and `strokeWidth` property is not working as mentioned in document. Is this a open issue or something I am missing. 

Do you please share any demo having dependency module integrated with mentioned properties.

I have created the dependency array in below way.

const objDependacy = {
                      id: new Date().valueOf(),
                      fromId: '#componentFromId#'
                      toId: '#componentToId#',
                      stroke: 'black',  
                      strokeWidth: 15,
                      arrowSize: 1,
                 };
  this.dependancies.push(objDependacy);`

**Comment by dgastudio** [comment]
same here
