### ISSUE TITLE
GanttOptions: Cannot destructure property 'toggle' of '__vite_ssr_import_1__.getContext(...)' as it is undefined.

### ISSUE THREAD

**Issue by MichelDSchmid** [ANovokmet/svelte-gantt#55]
Hi

I am currently trying to create a first draft of a Gantt chart using this library. So far so good, but as soon as I want to include GanttOptions as well, the error message mentioned in the title comes up. 
The message is triggered on the line: let { toggle, optionsStream } = getContext('options'); in GanttOptions.svelte. However, I have already checked everything several times and I can't find any error. 
Does anyone know what the problem could be?

Thanks a lot

Mike

**Comment by ANovokmet** [comment]
Are you trying to run the demo within another app? How are you including GanttOptions?

**Comment by MichelDSchmid** [comment]
Yes I'm running the demo as a subpage of a sveltekit project.

```
import { SvelteGantt, SvelteGanttDependencies, SvelteGanttTable, MomentSvelteGanttDateAdapter, SvelteGanttExternal } from 'svelte-gantt';
import { onMount, getContext } from 'svelte';
import {time} from '$lib/utils';
import moment from 'moment';
import GanttOptions from '$lib/GanttOptions.svelte';
```


without the GanttOptions is it running. I assume I have to read once more the document section about the context in the svelte docu ....

**Comment by MichelDSchmid** [comment]
OK, my fault, sorry! I initialised context wrong ....
Thanks for your hint about another app ...

regards
Mike

**Comment by torphix** [comment]
@MichelDSchmid Hi how did your fix this?
