### ISSUE TITLE
Possibility to override/deactivate the onDateSelected method

### ISSUE THREAD

**Issue by V-Py** [ANovokmet/svelte-gantt#56]
Hello,
It would be nice to be able to override and/or deactivate the onDateSelected function launched with the on:click event in the ColumnHeaderRow component. My specific need being to change the headers units and/or the columnUnit after clicking on the ColumnHeader. Or at least deactivate the possibility to click on the headers so it won't mess with my layout (ie different units depending of the timescale used)

**ColumnHeaderRow.svelte** (rows 52 - 57)
`    {#each _headers as _header}
        <div class="column-header-cell" class:sticky={header.sticky} style="width:{_header.width}px" on:click="{() => dispatch('dateSelected', { from: _header.from, to: _header.to, unit: _header.unit })}">
            <div class="column-header-cell-label">{_header.label || 'N/A'}</div>
        </div>
    {/each}`

**Gantt.svelte** (rows 393 - 396)
`    function onDateSelected(event) {
        $_from = event.detail.from;
        $_to = event.detail.to;
    }`

I can maybe try it and do a pull request if you don't have time to treat this. Since I need it for my projects, I'll implement it anyway locally otherwise.

Thank you for your time and you response

**Comment by V-Py** [comment]
Fixed with 22a977996684f46e13f38864da7edeb0eae6b30d
Access to the dateSelected event in the gantt api gives the ability to launch custom code after clicking on the ColumnHeaderRow component

**Comment by labs20** [comment]
I got it disabled this way:

``
.column-header-cell {
    pointer-events: none;
}
``

This click behaviour should be bounded to a boolean prop IMHO.

Hope it helps someone.
