### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by dgastudio** [ANovokmet/svelte-gantt#58]
Is it possible to disable all events for tasks? I mean make some kind of read-only mode

Thank you

**Comment by V-Py** [comment]
Hello, what do you mean by read-only ? 
Like not being able to move tasks ? You can already use the `enableDragging ` property on both row and task to disable any move.
Or you want to also disabled the selected Task effect ? You can disable the css if so ?

**Comment by dgastudio** [comment]
hello @V-Py 
yes, thank you, is what i have already done
have a good day!
