### ISSUE TITLE
Task bar drawing start position error

### ISSUE THREAD

**Issue by mfkwgizhoujian** [ANovokmet/svelte-gantt#65]
If the 'from' property is not set to the whole time, the starting position of the task bar is drawn incorrectly and will move forward.
The following figure is the official example. Draw the correct screenshot. The 'from' property value is '8:00'.
<img width="1682" alt="image" src="https://user-images.githubusercontent.com/33543763/163383455-5b8b05d3-e4bc-40c5-a12a-2214b7675724.png">

But if i change the 'from' property's value to '8:30', the starting position of the task bar is drawn incorrectly and will move forward.
The screenshot is as follows:
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/33543763/163384206-a14f47f9-b8f1-476e-9524-be85e023eaaf.png">

**Comment by ANovokmet** [comment]
Successfully reproduced, thank you. Working on it.

**Comment by ANovokmet** [comment]
There was an issue when timeline does not start at a rounded time, eg. 6:30. Now if timeline starts at 6:30 the headers will show for 1 hour intervals starting at from, eg. 6:30, 7:30, 8:30... so this is "fixed".

If we wanted for timeline to start at 6:30 but show headers for 7:00, 8:00, etc, we will need a different solution, perhaps some kind of startOffset (eg. `startOffset: 1800` moves the headers 30 minutes forward) value on a header, or a setting that specified if header should be rounded down (eg. `roundToUnit: true`).
