### ISSUE TITLE
How can we show start time and stop time in task gantt?

### ISSUE THREAD

**Issue by ANovokmet** [ANovokmet/svelte-gantt#7]
How can we show start time and stop time in task gantt?

_Originally posted by @mstsargin in https://github.com/ANovokmet/svelte-gantt/pull/6#issuecomment-714922858_

**Comment by ANovokmet** [comment]
Tasks contain moment which can be formatted and used in labels as you wish.
You can define `taskContent` for each task like this:
```javascript
const options = {
    taskContent: (task) => `${task.label} ${task.from.format('HH:mm')}`
}
```
or you can update the label in the change event (happens before the actual change in the Gantt store)
```javascript
gantt.api.tasks.on.change(([data]) => {
    const task = data.task.model;
    // be sure to add the "name" property
    task.label = `${task.name} ${task.from.format('HH:mm')}`;
});
```

**Comment by kesyous** [comment]
Very thanks,
Can we move the conflicting others forward?

**Comment by ANovokmet** [comment]
> Very thanks,
> Can we move the conflicting others forward?

I suggest you find the conflicting tasks in the source collection, move their `from` and `to` and use `gantt.$set({tasks: updatedTasks})`. 

Gantt exposes a function `updateTask(task)`, that upserts a single task, but something like `upsertAll(tasks)` would be nice too.
