### ISSUE TITLE
timeRange classes not working

### ISSUE THREAD

**Issue by victordcqx** [ANovokmet/svelte-gantt#71]
Nice work on the chart!
But I dont seem to be able to add classes to the timeRanges
It works for the tasks

```
timeRanges: [
      {
        id: 1,
        from: Date.parse("2022-05-16T12:25"),
        to: Date.parse("2022-05-16T12:50"),
        classes: "green",
        label: "test",
      },
      {
        id: 2,
        from: Date.parse("2022-05-16T14:25"),
        to: Date.parse("2022-05-16T14:50"),
        classes: ["currentTime"],
        label: "test2",
      },
    ]
```
![image](https://user-images.githubusercontent.com/105709900/168770763-5bb378a8-8d0a-4217-89b7-cb44614a3024.png)
![image](https://user-images.githubusercontent.com/105709900/168771096-fa10bb59-3254-4d71-a240-a6ee4d8151d5.png)

version "4.0.3-beta"

**Comment by V-Py** [comment]
Hi, you are 100% right, the `classes` property was not passed for the timeRanges. 
Must be fixed now :)

**Comment by victordcqx** [comment]
Thanks for the quick reaction!

It doesnt seem to upgrade through npm though... Is that a different version? Or does it take a while for npm to fetch the new update?

Also it seems you only updated the TimeRangeHeader, and not the TimeRange.
I would like to add classes to both.

**Comment by V-Py** [comment]
Hello,
You're right the changes weren't publish to npm, forgot to do it :x 
It must be good now !
I reopened your issue to add the class to the TimeRange too

**Comment by V-Py** [comment]
Fixed it, I'll republish a new version with the class property passed to TimeRange during the day,

**Comment by victordcqx** [comment]
Thanks a lot!

The header now has the class :)

**Comment by victordcqx** [comment]
@V-Py 
Hey, it seems you have not yet pushed the update to npm

**Comment by V-Py** [comment]
Yeah my bad, at the time I wanted to wait another modification to push it and didn't have the time since.
Must be good by now
