### ISSUE TITLE
Task background-color

### ISSUE THREAD

**Issue by morimasu3590** [ANovokmet/svelte-gantt#74]
Hello, 
I'm currently trying to learn about initiate the svelte-gantt. 
and I try to create a copy  from the example that you have in /demo/src/route/tree.svelte and just do exactly the same configuration for the options, especially for tasks.

![image](https://user-images.githubusercontent.com/18520601/168967490-693ac9b3-23aa-4654-aef6-ec9100d7ee26.png).

It is set as "orange" on classes for example of the first three task example.

But I'm still got the default task background-color for that which is blue
![image](https://user-images.githubusercontent.com/18520601/168967828-7e58b822-b593-4f07-8a8f-4b1d990c95d0.png)

Anything else that need to be configured to get the "orange" task background-color just like the example?

![image](https://user-images.githubusercontent.com/18520601/168968062-6addddd8-3042-4838-830c-69d1037253a1.png)

thank you for your time.

**Comment by V-Py** [comment]
Hello, can you confirm you have the `.sg-task.orange` properties in the gantt-default.css file and you are loading this file please ? 
And can you also verify with the inspector that your tasks have the `orange` class successfully added ?
Like this : 
![image](https://user-images.githubusercontent.com/59333024/168971045-e1a773fa-1f1d-48cc-bb8d-f2c7b8fcfd1d.png)

**Comment by morimasu3590** [comment]
It work after I load the gantt-default.css thank you. 
![image](https://user-images.githubusercontent.com/18520601/169215092-2cae70c7-4a30-4aec-bc8e-3fb2ffc37d02.png)

So I need to load this file everytime when I want to use the default gantt css?
![image](https://user-images.githubusercontent.com/18520601/169215706-7c10da6b-18f8-4615-8a0e-52272472bc66.png)


by the way thank you for the feedback

**Comment by morimasu3590** [comment]
It work after I load the gantt-default.css thank you.
