### ISSUE TITLE
Add milestones

### ISSUE THREAD

**Issue by Primenotes** [ANovokmet/svelte-gantt#79]
Hey, is there a 'reason' why the milestone entity is currently not used (e.g. performance)? (https://github.com/ANovokmet/svelte-gantt/blob/master/src/entities/Milestone.svelte)

Otherwise I can try to implement it by copying / adding it to tasks environment.

**Comment by Primenotes** [comment]
I think its better to use existing taskStore and display tasks as milestones depending on a condition (e.g. isMilestone: boolean).
Other thoughts about that?

**Comment by V-Py** [comment]
Hello, 
I don't know why it is currently not used, frankly I think you're right and that the best way atm is to use tasks with special configuration as Milestone.
But I'll still have a look at it to see if it can be used easily

**Comment by ANovokmet** [comment]
You are right, the best way is to use tasks with a special configuration. I implemented it as a separate component at first, but it resulted in too much duplicated code. 

In v4.1 this functionality is returned: Now, a task can be a milestone if the task `type` property is set to `'milestone'`. This disables resizing and renders the task as a diamond shape at the position of the task's start date.
