### ISSUE TITLE
Peer dependencies

### ISSUE THREAD

**Issue by craigboman** [ANovokmet/svelte-gantt#82]
When using pnpm to build in the /Demo, I got a peer dependencies issue that may need to be resolved. Looks like there are two different dependency requirements for two different typescript packages. Should we update this? Love svelte-gantt, by the way; great job. :)
<img width="873" alt="Screen Shot 2022-06-02 at 2 02 22 PM" src="https://user-images.githubusercontent.com/17816740/171696976-faa84bfc-7f7b-46c8-a120-1080f1dc0ad1.png">
.

**Comment by V-Py** [comment]
Hi, I saw your pull request, you are right, we should update these packages, I just need to find the time to give it a detailed look to define if there isn't any problem doing it 😅

**Comment by V-Py** [comment]
Should be fixed since I updated all the packages in #145
