### ISSUE TITLE
NPM package?

### ISSUE THREAD

**Issue by AlexBHarley** [ANovokmet/svelte-gantt#9]
Hey, really nice library. It is hard to find Gantt charts with permissive licenses.

Any thoughts on publishing an NPM package? I think it'd really help adoption.

**Comment by ANovokmet** [comment]
Thanks for the nice words. 

I was thinking about publishing it on NPM, haven't really got around to do it. Glad to hear there's interest, it will be done.

**Comment by fabiiomiiguel** [comment]
Yes that would be nice and really helpful :+1:

**Comment by ANovokmet** [comment]
You can now install `svelte-gantt` from npm 🚀, Thanks for trying it out.

https://www.npmjs.com/package/svelte-gantt

Feel free to post any issues you come across.
