### ISSUE TITLE
Use as real svelte component

### ISSUE THREAD

**Issue by bherbruck** [ANovokmet/svelte-gantt#94]
Is there a way to use this as a real svelte component instead of using refs and binding all the attributes?

If not, it would be nice if we could have a fully-typed svelte component of the [Gantt component](https://github.com/ANovokmet/svelte-gantt/blob/master/src/Gantt.svelte) (I notice some of the types are incomplete), maybe in a scoped package like `@svelte-gantt/svelte`.

**Comment by janosh** [comment]
Maybe port the demo site to SvelteKit in the process.

**Comment by ANovokmet** [comment]
Svelte components in v4.1 are now packaged. Also, the demo page uses SvelteKit.
