### ISSUE TITLE
need the svelte-gantt for angularJS

### ISSUE THREAD

**Issue by emazzu** [ANovokmet/svelte-gantt#96]
is it possible ??

**Comment by V-Py** [comment]
Well, svelte-gantt is written with Svelte but compiled in JS so you should be able to use it with any JS framework ? 
Can you explain your question ?

**Comment by emazzu** [comment]
I need, the gantt diagram, but I need add to angularJS version 1.x project, and I like your component, !!!
is it posible ?? it work on angularJS 1.x. ?? is there documentation for these ???
Regards
Eduardo from Argentina

**Comment by V-Py** [comment]
I don't understand your question tbh, you want to use it with Angular and it's not working ?
